# Generated by Django 3.0 on 2021-06-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('user_name', models.CharField(db_index=True, max_length=50, verbose_name='用户名')),
                ('head_img', models.CharField(max_length=200, verbose_name='头像')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('openid', models.CharField(max_length=30, verbose_name='openid')),
                ('unionid', models.CharField(max_length=30, verbose_name='unionid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
