# Generated by Django 3.0 on 2021-06-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodData',
            fields=[
                ('mood_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('text', models.TextField(max_length=300, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '心情表',
                'verbose_name_plural': '心情表',
            },
        ),
        migrations.CreateModel(
            name='TimeClass',
            fields=[
                ('time_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10, verbose_name='类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '时间分类表',
                'verbose_name_plural': '时间分类表',
            },
        ),
        migrations.CreateModel(
            name='MoodValue',
            fields=[
                ('mood_value_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.FloatField(verbose_name='心情值')),
                ('text', models.TextField(max_length=500, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mood_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_moodData', to='moodData.MoodData', verbose_name='时间分类')),
            ],
            options={
                'verbose_name': '心情值',
                'verbose_name_plural': '心情值',
            },
        ),
        migrations.CreateModel(
            name='MoodLabel',
            fields=[
                ('mood_label_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_mood_label', to='users.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '心情表标签',
                'verbose_name_plural': '心情表标签',
            },
        ),
        migrations.AddField(
            model_name='mooddata',
            name='mood_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodData.MoodLabel', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='mooddata',
            name='timeClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_moodData', to='moodData.TimeClass', verbose_name='时间分类'),
        ),
    ]
